
import java.awt.Component;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 1100167246
 */
public class EmployeeList extends javax.swing.JFrame {
    //Displays all employees for a specified company
    /**
     * Creates new form EmployeeList
     */
    ArrayList<String> EmployeeList = new ArrayList();
    String[][] Employees;
    int count = 1;
    Employer Empr;
    private Component jDialog1;
    
    public EmployeeList() throws IOException {
        //Create EmployeeList with no employer
        setTitle("AHS FBLA Desktop Application - " + Empr);
        initComponents();
    }
    
    public EmployeeList(String employer) throws IOException {
        //Create EmployeeList with set Employer
        Employer empr = new Employer(employer);
        setTitle("AHS FBLA Desktop Application - " + empr.getData(1));
        initEmployeeList(employer);
        initComponents();
    }
    
    /**
     *
     * @throws IOException
     */
    public void initEmployeeList(String employer) throws IOException
    {
        //Set the EmployeeList's data to Employees of given Employer 
        BufferedReader CSVFile = new BufferedReader(new FileReader("CSVFiles\\Employees.txt"));
        String dataRow = CSVFile.readLine();
        while (dataRow != null)
        {
            String[] dataArray = dataRow.split(",");
                EmployeeList.add(dataArray[0]);
            dataRow = CSVFile.readLine();
        }
        CSVFile.close();
        FieldPlacement FP = new FieldPlacement();
        Employees = new String[EmployeeList.size()][5];
        for(int i=1; i<EmployeeList.size(); i++)
        {
            String en = EmployeeList.get(i);
            Employee Emp = new Employee(en);
            Evaluation Eval = new Evaluation(en,1);
            Empr = new Employer(employer);
            if(employer.equals(FP.getData(i,1)))
            {
                Employees[i-count][0] = en;
                Employees[i-count][1] = Emp.getData(1) + " " + Emp.getData(2);
                if(Eval.getData(15) == null)
                {
                    Employees[i-count][2] = "No Score";
                }
                else
                {
                    Employees[i-count][2] = Eval.getData(15);
                }
                if(Eval.getData(4) == null)
                {
                    Employees[i-count][3] = "No Date";
                }
                else
                {
                    Employees[i-count][3] = Eval.getData(4);
                }
                if(Eval.getData(16) != null && Eval.getData(16).equals("true"))
                {
                    Employees[i-count][4] = "Yes";
                }
                else
                {
                    Employees[i-count][4] = "No";
                }
            }
            else
            {
                count++;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            Employees,
            new String [] {
                "ID Number", "Name", "Average Score", "Next Evaluation", "Recommendation"
            }
        ));
        jTable1.setName(null);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Evaluate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Report");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Creates Evaluation Form for selected Employee from Table
        if(jTable1.getSelectedRow()>=0)
        {
            try {
                Employee employee = new Employee(""+jTable1.getValueAt(jTable1.getSelectedRow(),0));
                if(employee.getData(1) !=null)
                {
                    EvaluationForm evalForm = new EvaluationForm(employee, Empr);
                    evalForm.setLocationRelativeTo(null);
                    evalForm.setVisible(true);
                    setVisible(false);
                }
                else
                {
                    JOptionPane.showMessageDialog(jDialog1,
                        "Please select a valid employee");
                }
            } catch (IOException ex) {
                Logger.getLogger(EmployeeList.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(jDialog1,
                    "Please select a valid employee");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Close EmpoyeeList
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Run report for selected Employee from table
        Employee employee;
        if(jTable1.getSelectedRow()>=0)
        {
            try {
                employee = new Employee(""+jTable1.getValueAt(jTable1.getSelectedRow(),0));
                if(employee.getData(1) !=null)
                {  
                    Evaluation Eval = new Evaluation(employee.getData(0),1);
                    System.out.println(Eval.getData(5));
                    if(!Eval.getData(5).equals("null"))
                    {
                        EmployeeReport employeereport = new EmployeeReport(employee);
                        employeereport.setLocationRelativeTo(null);
                        employeereport.setVisible(true);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(jDialog1,
                        "Please select an employee that has been evaluated");
                    }
                }
                else
                {
                JOptionPane.showMessageDialog(jDialog1,
                        "Please select a valid employee");
                }
            } catch (IOException ex) {
                Logger.getLogger(EmployeeList.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(jDialog1,
                    "Please select a valid employee");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EmployeeList().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(EmployeeList.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
